apiVersion: v2
name: trmnl
description: A Helm chart for deploying the TRMNL (Terminus) self-hosted application on Kubernetes.
type: application
version: 0.1.0
appVersion: "1.7.5"
home: https://usetrmnl.com
sources:
  - https://github.com/usetrmnl/terminus
keywords:
  - trmnl
  - terminus
  - e-ink
  - dashboard
maintainers:
  - name: NCO
dependencies:
  - name: postgresql
    version: 18.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: db.internal.enabled
  - name: valkey
    version: 5.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: valkey.enabled
  - name: common
    version: 2.36.0
    repository: https://charts.bitnami.com/bitnami
