{{- if not .Values.terminus.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trmnl.fullname" . }}
  labels:
    {{- include "trmnl.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "trmnl.databaseUrl" . | quote }}
  APP_SECRET: {{ .Values.terminus.appSecret | quote }}
{{- end }}
