{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trmnl.serviceAccountName" . }}
  labels:
    {{- include "trmnl.labels" . | nindent 4 }}
  {{- with (merge (.Values.serviceAccount.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
